sudo: required

services:
  - docker

install: ./docker-build.sh
script: ./docker-test.sh
after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then ./docker-push.sh; fi
